In [1]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn import metrics
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

In [6]:
df = pd.read_csv("/content/drive/MyDrive/rp/BestOneYet.csv")

In [7]:
df.head()

,Unnamed: 0,Optimum Time quantum,Avg Arrival Time,Max Arrival Time,Min Arrival Time,Avg Burst Time,Max Burst Time,Min Burst Time,Total Completion Time,Number of processes
0,0,10,4.833333,9,1,7.333333,10,2,44,6
1,1,10,5.800000,8,3,8.400000,12,4,42,5
2,2,15,4.333333,8,0,9.333333,15,6,84,9
3,3,9,5.888889,9,1,6.444444,9,2,58,9
4,4,14,5.000000,10,1,8.600000,15,3,86,10

In [8]:
X = df.drop(['Optimum Time quantum', 'Unnamed: 0'], axis = 'columns')
y = df['Optimum Time quantum']

In [9]:
X.head()

,Avg Arrival Time,Max Arrival Time,Min Arrival Time,Avg Burst Time,Max Burst Time,Min Burst Time,Total Completion Time,Number of processes
0,4.833333,9,1,7.333333,10,2,44,6
1,5.800000,8,3,8.400000,12,4,42,5
2,4.333333,8,0,9.333333,15,6,84,9
3,5.888889,9,1,6.444444,9,2,58,9
4,5.000000,10,1,8.600000,15,3,86,10

In [10]:
y.head()

0    10
1    10
2    15
3     9
4    14
Name: Optimum Time quantum, dtype: int64

In [11]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("Size and shape of X_train respectively are",X_train.size,"and",X_train.shape)
print("Size and shape of X_test respectively are",X_test.size,"and",X_test.shape)
print("Size and shape of y_train respectively are",y_train.size,"and",y_train.shape)
print("Size and shape of y_test respectively are",y_test.size,"and",y_test.shape)

Size and shape of X_train respectively are 64000 and (8000, 8)
Size and shape of X_test respectively are 16000 and (2000, 8)
Size and shape of y_train respectively are 8000 and (8000,)
Size and shape of y_test respectively are 2000 and (2000,)

In [19]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [21]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2score = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("rmse:", rmse)
print("r2score:", r2score)

Mean Squared Error: 4.05225
Mean Absolute Error: 1.0695
rmse: 2.013020119124496
r2score: 0.2709687888825639